from setuptools import setup

setup(
    name='SistemasAutonomos-DL',
    version='',
    packages=['venv.lib.python3.6.site-packages.PIL', 'venv.lib.python3.6.site-packages.absl',
              'venv.lib.python3.6.site-packages.absl.flags', 'venv.lib.python3.6.site-packages.absl.logging',
              'venv.lib.python3.6.site-packages.absl.testing', 'venv.lib.python3.6.site-packages.absl.third_party',
              'venv.lib.python3.6.site-packages.absl.third_party.unittest3_backport',
              'venv.lib.python3.6.site-packages.gast', 'venv.lib.python3.6.site-packages.grpc',
              'venv.lib.python3.6.site-packages.grpc.beta', 'venv.lib.python3.6.site-packages.grpc._cython',
              'venv.lib.python3.6.site-packages.grpc._cython._cygrpc',
              'venv.lib.python3.6.site-packages.grpc.framework',
              'venv.lib.python3.6.site-packages.grpc.framework.common',
              'venv.lib.python3.6.site-packages.grpc.framework.foundation',
              'venv.lib.python3.6.site-packages.grpc.framework.interfaces',
              'venv.lib.python3.6.site-packages.grpc.framework.interfaces.base',
              'venv.lib.python3.6.site-packages.grpc.framework.interfaces.face',
              'venv.lib.python3.6.site-packages.grpc.experimental', 'venv.lib.python3.6.site-packages.h5py',
              'venv.lib.python3.6.site-packages.h5py._hl', 'venv.lib.python3.6.site-packages.h5py.tests',
              'venv.lib.python3.6.site-packages.h5py.tests.hl', 'venv.lib.python3.6.site-packages.h5py.tests.old',
              'venv.lib.python3.6.site-packages.pytz', 'venv.lib.python3.6.site-packages.pywt',
              'venv.lib.python3.6.site-packages.pywt.data', 'venv.lib.python3.6.site-packages.pywt._extensions',
              'venv.lib.python3.6.site-packages.yaml', 'venv.lib.python3.6.site-packages.astor',
              'venv.lib.python3.6.site-packages.keras', 'venv.lib.python3.6.site-packages.keras.utils',
              'venv.lib.python3.6.site-packages.keras.engine', 'venv.lib.python3.6.site-packages.keras.layers',
              'venv.lib.python3.6.site-packages.keras.legacy', 'venv.lib.python3.6.site-packages.keras.backend',
              'venv.lib.python3.6.site-packages.keras.datasets', 'venv.lib.python3.6.site-packages.keras.wrappers',
              'venv.lib.python3.6.site-packages.keras.applications',
              'venv.lib.python3.6.site-packages.keras.preprocessing', 'venv.lib.python3.6.site-packages.numpy',
              'venv.lib.python3.6.site-packages.numpy.ma', 'venv.lib.python3.6.site-packages.numpy.ma.tests',
              'venv.lib.python3.6.site-packages.numpy.doc', 'venv.lib.python3.6.site-packages.numpy.fft',
              'venv.lib.python3.6.site-packages.numpy.fft.tests', 'venv.lib.python3.6.site-packages.numpy.lib',
              'venv.lib.python3.6.site-packages.numpy.lib.tests', 'venv.lib.python3.6.site-packages.numpy.core',
              'venv.lib.python3.6.site-packages.numpy.core.tests', 'venv.lib.python3.6.site-packages.numpy.f2py',
              'venv.lib.python3.6.site-packages.numpy.f2py.tests', 'venv.lib.python3.6.site-packages.numpy.tests',
              'venv.lib.python3.6.site-packages.numpy.compat', 'venv.lib.python3.6.site-packages.numpy.linalg',
              'venv.lib.python3.6.site-packages.numpy.linalg.tests', 'venv.lib.python3.6.site-packages.numpy.random',
              'venv.lib.python3.6.site-packages.numpy.random.tests', 'venv.lib.python3.6.site-packages.numpy.testing',
              'venv.lib.python3.6.site-packages.numpy.testing.tests',
              'venv.lib.python3.6.site-packages.numpy.testing.nose_tools',
              'venv.lib.python3.6.site-packages.numpy.distutils',
              'venv.lib.python3.6.site-packages.numpy.distutils.tests',
              'venv.lib.python3.6.site-packages.numpy.distutils.command',
              'venv.lib.python3.6.site-packages.numpy.distutils.fcompiler',
              'venv.lib.python3.6.site-packages.numpy.matrixlib',
              'venv.lib.python3.6.site-packages.numpy.matrixlib.tests',
              'venv.lib.python3.6.site-packages.numpy.polynomial',
              'venv.lib.python3.6.site-packages.numpy.polynomial.tests', 'venv.lib.python3.6.site-packages.scipy',
              'venv.lib.python3.6.site-packages.scipy.io', 'venv.lib.python3.6.site-packages.scipy.io.arff',
              'venv.lib.python3.6.site-packages.scipy.io.arff.tests', 'venv.lib.python3.6.site-packages.scipy.io.tests',
              'venv.lib.python3.6.site-packages.scipy.io.matlab',
              'venv.lib.python3.6.site-packages.scipy.io.matlab.tests',
              'venv.lib.python3.6.site-packages.scipy.io.harwell_boeing',
              'venv.lib.python3.6.site-packages.scipy.io.harwell_boeing.tests',
              'venv.lib.python3.6.site-packages.scipy.odr', 'venv.lib.python3.6.site-packages.scipy.odr.tests',
              'venv.lib.python3.6.site-packages.scipy._lib', 'venv.lib.python3.6.site-packages.scipy._lib.tests',
              'venv.lib.python3.6.site-packages.scipy.misc', 'venv.lib.python3.6.site-packages.scipy.misc.tests',
              'venv.lib.python3.6.site-packages.scipy.stats', 'venv.lib.python3.6.site-packages.scipy.stats.tests',
              'venv.lib.python3.6.site-packages.scipy.linalg', 'venv.lib.python3.6.site-packages.scipy.linalg.tests',
              'venv.lib.python3.6.site-packages.scipy.signal', 'venv.lib.python3.6.site-packages.scipy.signal.tests',
              'venv.lib.python3.6.site-packages.scipy.signal.windows', 'venv.lib.python3.6.site-packages.scipy.sparse',
              'venv.lib.python3.6.site-packages.scipy.sparse.tests',
              'venv.lib.python3.6.site-packages.scipy.sparse.linalg',
              'venv.lib.python3.6.site-packages.scipy.sparse.linalg.eigen',
              'venv.lib.python3.6.site-packages.scipy.sparse.linalg.eigen.arpack',
              'venv.lib.python3.6.site-packages.scipy.sparse.linalg.eigen.arpack.tests',
              'venv.lib.python3.6.site-packages.scipy.sparse.linalg.eigen.lobpcg',
              'venv.lib.python3.6.site-packages.scipy.sparse.linalg.eigen.lobpcg.tests',
              'venv.lib.python3.6.site-packages.scipy.sparse.linalg.tests',
              'venv.lib.python3.6.site-packages.scipy.sparse.linalg.dsolve',
              'venv.lib.python3.6.site-packages.scipy.sparse.linalg.dsolve.tests',
              'venv.lib.python3.6.site-packages.scipy.sparse.linalg.isolve',
              'venv.lib.python3.6.site-packages.scipy.sparse.linalg.isolve.tests',
              'venv.lib.python3.6.site-packages.scipy.sparse.csgraph',
              'venv.lib.python3.6.site-packages.scipy.sparse.csgraph.tests',
              'venv.lib.python3.6.site-packages.scipy.cluster', 'venv.lib.python3.6.site-packages.scipy.cluster.tests',
              'venv.lib.python3.6.site-packages.scipy.fftpack', 'venv.lib.python3.6.site-packages.scipy.fftpack.tests',
              'venv.lib.python3.6.site-packages.scipy.ndimage', 'venv.lib.python3.6.site-packages.scipy.ndimage.tests',
              'venv.lib.python3.6.site-packages.scipy.spatial', 'venv.lib.python3.6.site-packages.scipy.spatial.tests',
              'venv.lib.python3.6.site-packages.scipy.special', 'venv.lib.python3.6.site-packages.scipy.special.tests',
              'venv.lib.python3.6.site-packages.scipy.special._precompute',
              'venv.lib.python3.6.site-packages.scipy.optimize', 'venv.lib.python3.6.site-packages.scipy.optimize._lsq',
              'venv.lib.python3.6.site-packages.scipy.optimize.tests',
              'venv.lib.python3.6.site-packages.scipy.optimize._trlib',
              'venv.lib.python3.6.site-packages.scipy.optimize._trustregion_constr',
              'venv.lib.python3.6.site-packages.scipy.optimize._trustregion_constr.tests',
              'venv.lib.python3.6.site-packages.scipy.constants',
              'venv.lib.python3.6.site-packages.scipy.constants.tests',
              'venv.lib.python3.6.site-packages.scipy.integrate',
              'venv.lib.python3.6.site-packages.scipy.integrate._ivp',
              'venv.lib.python3.6.site-packages.scipy.integrate.tests',
              'venv.lib.python3.6.site-packages.scipy.interpolate',
              'venv.lib.python3.6.site-packages.scipy.interpolate.tests',
              'venv.lib.python3.6.site-packages.scipy._build_utils', 'venv.lib.python3.6.site-packages.wheel',
              'venv.lib.python3.6.site-packages.wheel.tool', 'venv.lib.python3.6.site-packages.wheel.signatures',
              'venv.lib.python3.6.site-packages.bleach', 'venv.lib.python3.6.site-packages.google.protobuf',
              'venv.lib.python3.6.site-packages.google.protobuf.util',
              'venv.lib.python3.6.site-packages.google.protobuf.pyext',
              'venv.lib.python3.6.site-packages.google.protobuf.compiler',
              'venv.lib.python3.6.site-packages.google.protobuf.internal',
              'venv.lib.python3.6.site-packages.google.protobuf.internal.import_test_package',
              'venv.lib.python3.6.site-packages.pandas', 'venv.lib.python3.6.site-packages.pandas.io',
              'venv.lib.python3.6.site-packages.pandas.io.sas', 'venv.lib.python3.6.site-packages.pandas.io.json',
              'venv.lib.python3.6.site-packages.pandas.io.formats',
              'venv.lib.python3.6.site-packages.pandas.io.msgpack',
              'venv.lib.python3.6.site-packages.pandas.io.clipboard', 'venv.lib.python3.6.site-packages.pandas.api',
              'venv.lib.python3.6.site-packages.pandas.api.types',
              'venv.lib.python3.6.site-packages.pandas.api.extensions', 'venv.lib.python3.6.site-packages.pandas.core',
              'venv.lib.python3.6.site-packages.pandas.core.util', 'venv.lib.python3.6.site-packages.pandas.core.tools',
              'venv.lib.python3.6.site-packages.pandas.core.arrays',
              'venv.lib.python3.6.site-packages.pandas.core.dtypes',
              'venv.lib.python3.6.site-packages.pandas.core.sparse',
              'venv.lib.python3.6.site-packages.pandas.core.groupby',
              'venv.lib.python3.6.site-packages.pandas.core.indexes',
              'venv.lib.python3.6.site-packages.pandas.core.reshape',
              'venv.lib.python3.6.site-packages.pandas.core.computation',
              'venv.lib.python3.6.site-packages.pandas.util', 'venv.lib.python3.6.site-packages.pandas._libs',
              'venv.lib.python3.6.site-packages.pandas._libs.tslibs', 'venv.lib.python3.6.site-packages.pandas.tests',
              'venv.lib.python3.6.site-packages.pandas.tests.io',
              'venv.lib.python3.6.site-packages.pandas.tests.io.sas',
              'venv.lib.python3.6.site-packages.pandas.tests.io.json',
              'venv.lib.python3.6.site-packages.pandas.tests.io.parser',
              'venv.lib.python3.6.site-packages.pandas.tests.io.formats',
              'venv.lib.python3.6.site-packages.pandas.tests.io.msgpack',
              'venv.lib.python3.6.site-packages.pandas.tests.api', 'venv.lib.python3.6.site-packages.pandas.tests.util',
              'venv.lib.python3.6.site-packages.pandas.tests.frame',
              'venv.lib.python3.6.site-packages.pandas.tests.tools',
              'venv.lib.python3.6.site-packages.pandas.tests.dtypes',
              'venv.lib.python3.6.site-packages.pandas.tests.scalar',
              'venv.lib.python3.6.site-packages.pandas.tests.scalar.period',
              'venv.lib.python3.6.site-packages.pandas.tests.scalar.interval',
              'venv.lib.python3.6.site-packages.pandas.tests.scalar.timedelta',
              'venv.lib.python3.6.site-packages.pandas.tests.scalar.timestamp',
              'venv.lib.python3.6.site-packages.pandas.tests.series',
              'venv.lib.python3.6.site-packages.pandas.tests.series.indexing',
              'venv.lib.python3.6.site-packages.pandas.tests.sparse',
              'venv.lib.python3.6.site-packages.pandas.tests.sparse.frame',
              'venv.lib.python3.6.site-packages.pandas.tests.sparse.series',
              'venv.lib.python3.6.site-packages.pandas.tests.tslibs',
              'venv.lib.python3.6.site-packages.pandas.tests.generic',
              'venv.lib.python3.6.site-packages.pandas.tests.groupby',
              'venv.lib.python3.6.site-packages.pandas.tests.groupby.aggregate',
              'venv.lib.python3.6.site-packages.pandas.tests.indexes',
              'venv.lib.python3.6.site-packages.pandas.tests.indexes.period',
              'venv.lib.python3.6.site-packages.pandas.tests.indexes.interval',
              'venv.lib.python3.6.site-packages.pandas.tests.indexes.datetimes',
              'venv.lib.python3.6.site-packages.pandas.tests.indexes.timedeltas',
              'venv.lib.python3.6.site-packages.pandas.tests.reshape',
              'venv.lib.python3.6.site-packages.pandas.tests.reshape.merge',
              'venv.lib.python3.6.site-packages.pandas.tests.tseries',
              'venv.lib.python3.6.site-packages.pandas.tests.tseries.offsets',
              'venv.lib.python3.6.site-packages.pandas.tests.indexing',
              'venv.lib.python3.6.site-packages.pandas.tests.indexing.interval',
              'venv.lib.python3.6.site-packages.pandas.tests.plotting',
              'venv.lib.python3.6.site-packages.pandas.tests.extension',
              'venv.lib.python3.6.site-packages.pandas.tests.extension.base',
              'venv.lib.python3.6.site-packages.pandas.tests.extension.json',
              'venv.lib.python3.6.site-packages.pandas.tests.extension.decimal',
              'venv.lib.python3.6.site-packages.pandas.tests.extension.category',
              'venv.lib.python3.6.site-packages.pandas.tests.internals',
              'venv.lib.python3.6.site-packages.pandas.tests.categorical',
              'venv.lib.python3.6.site-packages.pandas.tests.computation',
              'venv.lib.python3.6.site-packages.pandas.tools', 'venv.lib.python3.6.site-packages.pandas.types',
              'venv.lib.python3.6.site-packages.pandas.compat', 'venv.lib.python3.6.site-packages.pandas.compat.numpy',
              'venv.lib.python3.6.site-packages.pandas.errors', 'venv.lib.python3.6.site-packages.pandas.formats',
              'venv.lib.python3.6.site-packages.pandas.tseries', 'venv.lib.python3.6.site-packages.pandas.plotting',
              'venv.lib.python3.6.site-packages.pandas.computation', 'venv.lib.python3.6.site-packages.skimage',
              'venv.lib.python3.6.site-packages.skimage.io', 'venv.lib.python3.6.site-packages.skimage.io.tests',
              'venv.lib.python3.6.site-packages.skimage.io._plugins', 'venv.lib.python3.6.site-packages.skimage.data',
              'venv.lib.python3.6.site-packages.skimage.data.tests', 'venv.lib.python3.6.site-packages.skimage.draw',
              'venv.lib.python3.6.site-packages.skimage.draw.tests', 'venv.lib.python3.6.site-packages.skimage.util',
              'venv.lib.python3.6.site-packages.skimage.util.tests', 'venv.lib.python3.6.site-packages.skimage.color',
              'venv.lib.python3.6.site-packages.skimage.color.tests', 'venv.lib.python3.6.site-packages.skimage.graph',
              'venv.lib.python3.6.site-packages.skimage.graph.tests', 'venv.lib.python3.6.site-packages.skimage.future',
              'venv.lib.python3.6.site-packages.skimage.future.graph',
              'venv.lib.python3.6.site-packages.skimage.novice',
              'venv.lib.python3.6.site-packages.skimage.novice.tests',
              'venv.lib.python3.6.site-packages.skimage.viewer',
              'venv.lib.python3.6.site-packages.skimage.viewer.tests',
              'venv.lib.python3.6.site-packages.skimage.viewer.utils',
              'venv.lib.python3.6.site-packages.skimage.viewer.plugins',
              'venv.lib.python3.6.site-packages.skimage.viewer.viewers',
              'venv.lib.python3.6.site-packages.skimage.viewer.widgets',
              'venv.lib.python3.6.site-packages.skimage.viewer.canvastools',
              'venv.lib.python3.6.site-packages.skimage._shared',
              'venv.lib.python3.6.site-packages.skimage._shared.tests',
              'venv.lib.python3.6.site-packages.skimage.feature',
              'venv.lib.python3.6.site-packages.skimage.feature.tests',
              'venv.lib.python3.6.site-packages.skimage.filters',
              'venv.lib.python3.6.site-packages.skimage.filters.rank',
              'venv.lib.python3.6.site-packages.skimage.filters.rank.tests',
              'venv.lib.python3.6.site-packages.skimage.filters.tests',
              'venv.lib.python3.6.site-packages.skimage.measure',
              'venv.lib.python3.6.site-packages.skimage.measure.tests',
              'venv.lib.python3.6.site-packages.skimage.scripts', 'venv.lib.python3.6.site-packages.skimage.exposure',
              'venv.lib.python3.6.site-packages.skimage.exposure.tests',
              'venv.lib.python3.6.site-packages.skimage.external',
              'venv.lib.python3.6.site-packages.skimage.external.tifffile',
              'venv.lib.python3.6.site-packages.skimage.transform',
              'venv.lib.python3.6.site-packages.skimage.transform.tests',
              'venv.lib.python3.6.site-packages.skimage.morphology',
              'venv.lib.python3.6.site-packages.skimage.morphology.tests',
              'venv.lib.python3.6.site-packages.skimage.restoration',
              'venv.lib.python3.6.site-packages.skimage.restoration.tests',
              'venv.lib.python3.6.site-packages.skimage.segmentation',
              'venv.lib.python3.6.site-packages.skimage.segmentation.tests', 'venv.lib.python3.6.site-packages.sklearn',
              'venv.lib.python3.6.site-packages.sklearn.svm', 'venv.lib.python3.6.site-packages.sklearn.svm.tests',
              'venv.lib.python3.6.site-packages.sklearn.tree', 'venv.lib.python3.6.site-packages.sklearn.tree.tests',
              'venv.lib.python3.6.site-packages.sklearn.tests', 'venv.lib.python3.6.site-packages.sklearn.utils',
              'venv.lib.python3.6.site-packages.sklearn.utils.tests',
              'venv.lib.python3.6.site-packages.sklearn.utils.sparsetools',
              'venv.lib.python3.6.site-packages.sklearn.utils.sparsetools.tests',
              'venv.lib.python3.6.site-packages.sklearn.cluster',
              'venv.lib.python3.6.site-packages.sklearn.cluster.tests',
              'venv.lib.python3.6.site-packages.sklearn.metrics',
              'venv.lib.python3.6.site-packages.sklearn.metrics.tests',
              'venv.lib.python3.6.site-packages.sklearn.metrics.cluster',
              'venv.lib.python3.6.site-packages.sklearn.metrics.cluster.tests',
              'venv.lib.python3.6.site-packages.sklearn.mixture',
              'venv.lib.python3.6.site-packages.sklearn.mixture.tests',
              'venv.lib.python3.6.site-packages.sklearn.datasets',
              'venv.lib.python3.6.site-packages.sklearn.datasets.tests',
              'venv.lib.python3.6.site-packages.sklearn.ensemble',
              'venv.lib.python3.6.site-packages.sklearn.ensemble.tests',
              'venv.lib.python3.6.site-packages.sklearn.manifold',
              'venv.lib.python3.6.site-packages.sklearn.manifold.tests',
              'venv.lib.python3.6.site-packages.sklearn.externals',
              'venv.lib.python3.6.site-packages.sklearn.externals.joblib',
              'venv.lib.python3.6.site-packages.sklearn.neighbors',
              'venv.lib.python3.6.site-packages.sklearn.neighbors.tests',
              'venv.lib.python3.6.site-packages.sklearn.covariance',
              'venv.lib.python3.6.site-packages.sklearn.covariance.tests',
              'venv.lib.python3.6.site-packages.sklearn._build_utils',
              'venv.lib.python3.6.site-packages.sklearn.linear_model',
              'venv.lib.python3.6.site-packages.sklearn.linear_model.tests',
              'venv.lib.python3.6.site-packages.sklearn.__check_build',
              'venv.lib.python3.6.site-packages.sklearn.decomposition',
              'venv.lib.python3.6.site-packages.sklearn.decomposition.tests',
              'venv.lib.python3.6.site-packages.sklearn.preprocessing',
              'venv.lib.python3.6.site-packages.sklearn.preprocessing.tests',
              'venv.lib.python3.6.site-packages.sklearn.neural_network',
              'venv.lib.python3.6.site-packages.sklearn.neural_network.tests',
              'venv.lib.python3.6.site-packages.sklearn.model_selection',
              'venv.lib.python3.6.site-packages.sklearn.model_selection.tests',
              'venv.lib.python3.6.site-packages.sklearn.semi_supervised',
              'venv.lib.python3.6.site-packages.sklearn.semi_supervised.tests',
              'venv.lib.python3.6.site-packages.sklearn.gaussian_process',
              'venv.lib.python3.6.site-packages.sklearn.gaussian_process.tests',
              'venv.lib.python3.6.site-packages.sklearn.feature_selection',
              'venv.lib.python3.6.site-packages.sklearn.feature_selection.tests',
              'venv.lib.python3.6.site-packages.sklearn.feature_extraction',
              'venv.lib.python3.6.site-packages.sklearn.feature_extraction.tests',
              'venv.lib.python3.6.site-packages.sklearn.cross_decomposition',
              'venv.lib.python3.6.site-packages.sklearn.cross_decomposition.tests',
              'venv.lib.python3.6.site-packages.dateutil', 'venv.lib.python3.6.site-packages.dateutil.tz',
              'venv.lib.python3.6.site-packages.dateutil.parser', 'venv.lib.python3.6.site-packages.dateutil.zoneinfo',
              'venv.lib.python3.6.site-packages.external', 'venv.lib.python3.6.site-packages.external.absl_py',
              'venv.lib.python3.6.site-packages.external.absl_py.absl',
              'venv.lib.python3.6.site-packages.external.absl_py.absl.flags',
              'venv.lib.python3.6.site-packages.external.six_archive',
              'venv.lib.python3.6.site-packages.external.gast_archive',
              'venv.lib.python3.6.site-packages.external.gast_archive.gast',
              'venv.lib.python3.6.site-packages.external.astor_archive',
              'venv.lib.python3.6.site-packages.external.astor_archive.astor',
              'venv.lib.python3.6.site-packages.external.protobuf_archive',
              'venv.lib.python3.6.site-packages.external.protobuf_archive.python',
              'venv.lib.python3.6.site-packages.external.protobuf_archive.python.google',
              'venv.lib.python3.6.site-packages.external.protobuf_archive.python.google.protobuf',
              'venv.lib.python3.6.site-packages.external.protobuf_archive.python.google.protobuf.pyext',
              'venv.lib.python3.6.site-packages.external.protobuf_archive.python.google.protobuf.compiler',
              'venv.lib.python3.6.site-packages.external.protobuf_archive.python.google.protobuf.internal',
              'venv.lib.python3.6.site-packages.external.protobuf_archive.python.google.protobuf.internal.import_test_package',
              'venv.lib.python3.6.site-packages.external.protobuf_archive.python.compatibility_tests',
              'venv.lib.python3.6.site-packages.external.protobuf_archive.python.compatibility_tests.v2.5.0',
              'venv.lib.python3.6.site-packages.external.protobuf_archive.python.compatibility_tests.v2.5.0.tests',
              'venv.lib.python3.6.site-packages.external.protobuf_archive.python.compatibility_tests.v2.5.0.tests.google',
              'venv.lib.python3.6.site-packages.external.protobuf_archive.python.compatibility_tests.v2.5.0.tests.google.protobuf',
              'venv.lib.python3.6.site-packages.external.protobuf_archive.python.compatibility_tests.v2.5.0.tests.google.protobuf.internal',
              'venv.lib.python3.6.site-packages.external.termcolor_archive',
              'venv.lib.python3.6.site-packages.external.org_python_pypi_backports_weakref',
              'venv.lib.python3.6.site-packages.external.org_python_pypi_backports_weakref.backports',
              'venv.lib.python3.6.site-packages.html5lib', 'venv.lib.python3.6.site-packages.html5lib.trie',
              'venv.lib.python3.6.site-packages.html5lib.filters',
              'venv.lib.python3.6.site-packages.html5lib.serializer',
              'venv.lib.python3.6.site-packages.html5lib.treewalkers',
              'venv.lib.python3.6.site-packages.html5lib.treeadapters',
              'venv.lib.python3.6.site-packages.html5lib.treebuilders', 'venv.lib.python3.6.site-packages.markdown',
              'venv.lib.python3.6.site-packages.markdown.extensions', 'venv.lib.python3.6.site-packages.networkx',
              'venv.lib.python3.6.site-packages.networkx.tests', 'venv.lib.python3.6.site-packages.networkx.utils',
              'venv.lib.python3.6.site-packages.networkx.linalg', 'venv.lib.python3.6.site-packages.networkx.classes',
              'venv.lib.python3.6.site-packages.networkx.drawing', 'venv.lib.python3.6.site-packages.networkx.testing',
              'venv.lib.python3.6.site-packages.networkx.readwrite',
              'venv.lib.python3.6.site-packages.networkx.readwrite.json_graph',
              'venv.lib.python3.6.site-packages.networkx.algorithms',
              'venv.lib.python3.6.site-packages.networkx.algorithms.flow',
              'venv.lib.python3.6.site-packages.networkx.algorithms.tree',
              'venv.lib.python3.6.site-packages.networkx.algorithms.coloring',
              'venv.lib.python3.6.site-packages.networkx.algorithms.bipartite',
              'venv.lib.python3.6.site-packages.networkx.algorithms.community',
              'venv.lib.python3.6.site-packages.networkx.algorithms.operators',
              'venv.lib.python3.6.site-packages.networkx.algorithms.traversal',
              'venv.lib.python3.6.site-packages.networkx.algorithms.centrality',
              'venv.lib.python3.6.site-packages.networkx.algorithms.components',
              'venv.lib.python3.6.site-packages.networkx.algorithms.isomorphism',
              'venv.lib.python3.6.site-packages.networkx.algorithms.connectivity',
              'venv.lib.python3.6.site-packages.networkx.algorithms.approximation',
              'venv.lib.python3.6.site-packages.networkx.algorithms.assortativity',
              'venv.lib.python3.6.site-packages.networkx.algorithms.link_analysis',
              'venv.lib.python3.6.site-packages.networkx.algorithms.shortest_paths',
              'venv.lib.python3.6.site-packages.networkx.generators', 'venv.lib.python3.6.site-packages.werkzeug',
              'venv.lib.python3.6.site-packages.werkzeug.debug', 'venv.lib.python3.6.site-packages.werkzeug.contrib',
              'venv.lib.python3.6.site-packages.matplotlib', 'venv.lib.python3.6.site-packages.matplotlib.tri',
              'venv.lib.python3.6.site-packages.matplotlib.axes', 'venv.lib.python3.6.site-packages.matplotlib.cbook',
              'venv.lib.python3.6.site-packages.matplotlib.style', 'venv.lib.python3.6.site-packages.matplotlib.tests',
              'venv.lib.python3.6.site-packages.matplotlib.compat',
              'venv.lib.python3.6.site-packages.matplotlib.testing',
              'venv.lib.python3.6.site-packages.matplotlib.testing._nose',
              'venv.lib.python3.6.site-packages.matplotlib.testing._nose.plugins',
              'venv.lib.python3.6.site-packages.matplotlib.testing.jpl_units',
              'venv.lib.python3.6.site-packages.matplotlib.backends',
              'venv.lib.python3.6.site-packages.matplotlib.backends.qt_editor',
              'venv.lib.python3.6.site-packages.matplotlib.sphinxext',
              'venv.lib.python3.6.site-packages.matplotlib.sphinxext.tests',
              'venv.lib.python3.6.site-packages.matplotlib.projections', 'venv.lib.python3.6.site-packages.tensorflow',
              'venv.lib.python3.6.site-packages.tensorflow.core',
              'venv.lib.python3.6.site-packages.tensorflow.core.lib',
              'venv.lib.python3.6.site-packages.tensorflow.core.lib.core',
              'venv.lib.python3.6.site-packages.tensorflow.core.util',
              'venv.lib.python3.6.site-packages.tensorflow.core.debug',
              'venv.lib.python3.6.site-packages.tensorflow.core.example',
              'venv.lib.python3.6.site-packages.tensorflow.core.kernels',
              'venv.lib.python3.6.site-packages.tensorflow.core.kernels.boosted_trees',
              'venv.lib.python3.6.site-packages.tensorflow.core.grappler',
              'venv.lib.python3.6.site-packages.tensorflow.core.grappler.costs',
              'venv.lib.python3.6.site-packages.tensorflow.core.profiler',
              'venv.lib.python3.6.site-packages.tensorflow.core.protobuf',
              'venv.lib.python3.6.site-packages.tensorflow.core.framework',
              'venv.lib.python3.6.site-packages.tensorflow.tools',
              'venv.lib.python3.6.site-packages.tensorflow.tools.api',
              'venv.lib.python3.6.site-packages.tensorflow.tools.api.generator',
              'venv.lib.python3.6.site-packages.tensorflow.tools.api.generator.api',
              'venv.lib.python3.6.site-packages.tensorflow.tools.api.generator.api.nn',
              'venv.lib.python3.6.site-packages.tensorflow.tools.api.generator.api.nn.rnn_cell',
              'venv.lib.python3.6.site-packages.tensorflow.tools.api.generator.api.app',
              'venv.lib.python3.6.site-packages.tensorflow.tools.api.generator.api.data',
              'venv.lib.python3.6.site-packages.tensorflow.tools.api.generator.api.math',
              'venv.lib.python3.6.site-packages.tensorflow.tools.api.generator.api.sets',
              'venv.lib.python3.6.site-packages.tensorflow.tools.api.generator.api.test',
              'venv.lib.python3.6.site-packages.tensorflow.tools.api.generator.api.gfile',
              'venv.lib.python3.6.site-packages.tensorflow.tools.api.generator.api.image',
              'venv.lib.python3.6.site-packages.tensorflow.tools.api.generator.api.keras',
              'venv.lib.python3.6.site-packages.tensorflow.tools.api.generator.api.keras.utils',
              'venv.lib.python3.6.site-packages.tensorflow.tools.api.generator.api.keras.layers',
              'venv.lib.python3.6.site-packages.tensorflow.tools.api.generator.api.keras.losses',
              'venv.lib.python3.6.site-packages.tensorflow.tools.api.generator.api.keras.models',
              'venv.lib.python3.6.site-packages.tensorflow.tools.api.generator.api.keras.backend',
              'venv.lib.python3.6.site-packages.tensorflow.tools.api.generator.api.keras.metrics',
              'venv.lib.python3.6.site-packages.tensorflow.tools.api.generator.api.keras.datasets',
              'venv.lib.python3.6.site-packages.tensorflow.tools.api.generator.api.keras.datasets.imdb',
              'venv.lib.python3.6.site-packages.tensorflow.tools.api.generator.api.keras.datasets.mnist',
              'venv.lib.python3.6.site-packages.tensorflow.tools.api.generator.api.keras.datasets.cifar10',
              'venv.lib.python3.6.site-packages.tensorflow.tools.api.generator.api.keras.datasets.reuters',
              'venv.lib.python3.6.site-packages.tensorflow.tools.api.generator.api.keras.datasets.cifar100',
              'venv.lib.python3.6.site-packages.tensorflow.tools.api.generator.api.keras.datasets.fashion_mnist',
              'venv.lib.python3.6.site-packages.tensorflow.tools.api.generator.api.keras.datasets.boston_housing',
              'venv.lib.python3.6.site-packages.tensorflow.tools.api.generator.api.keras.wrappers',
              'venv.lib.python3.6.site-packages.tensorflow.tools.api.generator.api.keras.wrappers.scikit_learn',
              'venv.lib.python3.6.site-packages.tensorflow.tools.api.generator.api.keras.callbacks',
              'venv.lib.python3.6.site-packages.tensorflow.tools.api.generator.api.keras.estimator',
              'venv.lib.python3.6.site-packages.tensorflow.tools.api.generator.api.keras.optimizers',
              'venv.lib.python3.6.site-packages.tensorflow.tools.api.generator.api.keras.activations',
              'venv.lib.python3.6.site-packages.tensorflow.tools.api.generator.api.keras.constraints',
              'venv.lib.python3.6.site-packages.tensorflow.tools.api.generator.api.keras.applications',
              'venv.lib.python3.6.site-packages.tensorflow.tools.api.generator.api.keras.applications.vgg16',
              'venv.lib.python3.6.site-packages.tensorflow.tools.api.generator.api.keras.applications.vgg19',
              'venv.lib.python3.6.site-packages.tensorflow.tools.api.generator.api.keras.applications.nasnet',
              'venv.lib.python3.6.site-packages.tensorflow.tools.api.generator.api.keras.applications.densenet',
              'venv.lib.python3.6.site-packages.tensorflow.tools.api.generator.api.keras.applications.resnet50',
              'venv.lib.python3.6.site-packages.tensorflow.tools.api.generator.api.keras.applications.xception',
              'venv.lib.python3.6.site-packages.tensorflow.tools.api.generator.api.keras.applications.mobilenet',
              'venv.lib.python3.6.site-packages.tensorflow.tools.api.generator.api.keras.applications.inception_v3',
              'venv.lib.python3.6.site-packages.tensorflow.tools.api.generator.api.keras.applications.inception_resnet_v2',
              'venv.lib.python3.6.site-packages.tensorflow.tools.api.generator.api.keras.initializers',
              'venv.lib.python3.6.site-packages.tensorflow.tools.api.generator.api.keras.regularizers',
              'venv.lib.python3.6.site-packages.tensorflow.tools.api.generator.api.keras.preprocessing',
              'venv.lib.python3.6.site-packages.tensorflow.tools.api.generator.api.keras.preprocessing.text',
              'venv.lib.python3.6.site-packages.tensorflow.tools.api.generator.api.keras.preprocessing.image',
              'venv.lib.python3.6.site-packages.tensorflow.tools.api.generator.api.keras.preprocessing.sequence',
              'venv.lib.python3.6.site-packages.tensorflow.tools.api.generator.api.manip',
              'venv.lib.python3.6.site-packages.tensorflow.tools.api.generator.api.train',
              'venv.lib.python3.6.site-packages.tensorflow.tools.api.generator.api.train.queue_runner',
              'venv.lib.python3.6.site-packages.tensorflow.tools.api.generator.api.compat',
              'venv.lib.python3.6.site-packages.tensorflow.tools.api.generator.api.errors',
              'venv.lib.python3.6.site-packages.tensorflow.tools.api.generator.api.layers',
              'venv.lib.python3.6.site-packages.tensorflow.tools.api.generator.api.linalg',
              'venv.lib.python3.6.site-packages.tensorflow.tools.api.generator.api.losses',
              'venv.lib.python3.6.site-packages.tensorflow.tools.api.generator.api.bitwise',
              'venv.lib.python3.6.site-packages.tensorflow.tools.api.generator.api.contrib',
              'venv.lib.python3.6.site-packages.tensorflow.tools.api.generator.api.contrib.stat_summarizer',
              'venv.lib.python3.6.site-packages.tensorflow.tools.api.generator.api.logging',
              'venv.lib.python3.6.site-packages.tensorflow.tools.api.generator.api.metrics',
              'venv.lib.python3.6.site-packages.tensorflow.tools.api.generator.api.summary',
              'venv.lib.python3.6.site-packages.tensorflow.tools.api.generator.api.profiler',
              'venv.lib.python3.6.site-packages.tensorflow.tools.api.generator.api.spectral',
              'venv.lib.python3.6.site-packages.tensorflow.tools.api.generator.api.user_ops',
              'venv.lib.python3.6.site-packages.tensorflow.tools.api.generator.api.estimator',
              'venv.lib.python3.6.site-packages.tensorflow.tools.api.generator.api.estimator.export',
              'venv.lib.python3.6.site-packages.tensorflow.tools.api.generator.api.estimator.inputs',
              'venv.lib.python3.6.site-packages.tensorflow.tools.api.generator.api.python_io',
              'venv.lib.python3.6.site-packages.tensorflow.tools.api.generator.api.sysconfig',
              'venv.lib.python3.6.site-packages.tensorflow.tools.api.generator.api.graph_util',
              'venv.lib.python3.6.site-packages.tensorflow.tools.api.generator.api.saved_model',
              'venv.lib.python3.6.site-packages.tensorflow.tools.api.generator.api.saved_model.utils',
              'venv.lib.python3.6.site-packages.tensorflow.tools.api.generator.api.saved_model.loader',
              'venv.lib.python3.6.site-packages.tensorflow.tools.api.generator.api.saved_model.builder',
              'venv.lib.python3.6.site-packages.tensorflow.tools.api.generator.api.saved_model.main_op',
              'venv.lib.python3.6.site-packages.tensorflow.tools.api.generator.api.saved_model.constants',
              'venv.lib.python3.6.site-packages.tensorflow.tools.api.generator.api.saved_model.tag_constants',
              'venv.lib.python3.6.site-packages.tensorflow.tools.api.generator.api.saved_model.signature_constants',
              'venv.lib.python3.6.site-packages.tensorflow.tools.api.generator.api.saved_model.signature_def_utils',
              'venv.lib.python3.6.site-packages.tensorflow.tools.api.generator.api.initializers',
              'venv.lib.python3.6.site-packages.tensorflow.tools.api.generator.api.distributions',
              'venv.lib.python3.6.site-packages.tensorflow.tools.api.generator.api.distributions.bijectors',
              'venv.lib.python3.6.site-packages.tensorflow.tools.api.generator.api.feature_column',
              'venv.lib.python3.6.site-packages.tensorflow.tools.api.generator.api.resource_loader',
              'venv.lib.python3.6.site-packages.tensorflow.tools.dist_test',
              'venv.lib.python3.6.site-packages.tensorflow.tools.dist_test.server',
              'venv.lib.python3.6.site-packages.tensorflow.tools.pip_package',
              'venv.lib.python3.6.site-packages.tensorflow.tools.graph_transforms',
              'venv.lib.python3.6.site-packages.tensorflow.python',
              'venv.lib.python3.6.site-packages.tensorflow.python.lib',
              'venv.lib.python3.6.site-packages.tensorflow.python.lib.io',
              'venv.lib.python3.6.site-packages.tensorflow.python.ops',
              'venv.lib.python3.6.site-packages.tensorflow.python.ops.linalg',
              'venv.lib.python3.6.site-packages.tensorflow.python.ops.losses',
              'venv.lib.python3.6.site-packages.tensorflow.python.ops.distributions',
              'venv.lib.python3.6.site-packages.tensorflow.python.data',
              'venv.lib.python3.6.site-packages.tensorflow.python.data.ops',
              'venv.lib.python3.6.site-packages.tensorflow.python.data.util',
              'venv.lib.python3.6.site-packages.tensorflow.python.util',
              'venv.lib.python3.6.site-packages.tensorflow.python.util.protobuf',
              'venv.lib.python3.6.site-packages.tensorflow.python.debug',
              'venv.lib.python3.6.site-packages.tensorflow.python.debug.cli',
              'venv.lib.python3.6.site-packages.tensorflow.python.debug.lib',
              'venv.lib.python3.6.site-packages.tensorflow.python.debug.examples',
              'venv.lib.python3.6.site-packages.tensorflow.python.debug.wrappers',
              'venv.lib.python3.6.site-packages.tensorflow.python.eager',
              'venv.lib.python3.6.site-packages.tensorflow.python.keras',
              'venv.lib.python3.6.site-packages.tensorflow.python.keras._impl',
              'venv.lib.python3.6.site-packages.tensorflow.python.keras._impl.keras',
              'venv.lib.python3.6.site-packages.tensorflow.python.keras._impl.keras.utils',
              'venv.lib.python3.6.site-packages.tensorflow.python.keras._impl.keras.engine',
              'venv.lib.python3.6.site-packages.tensorflow.python.keras._impl.keras.layers',
              'venv.lib.python3.6.site-packages.tensorflow.python.keras._impl.keras.datasets',
              'venv.lib.python3.6.site-packages.tensorflow.python.keras._impl.keras.wrappers',
              'venv.lib.python3.6.site-packages.tensorflow.python.keras._impl.keras.applications',
              'venv.lib.python3.6.site-packages.tensorflow.python.keras._impl.keras.preprocessing',
              'venv.lib.python3.6.site-packages.tensorflow.python.keras.utils',
              'venv.lib.python3.6.site-packages.tensorflow.python.keras.layers',
              'venv.lib.python3.6.site-packages.tensorflow.python.keras.losses',
              'venv.lib.python3.6.site-packages.tensorflow.python.keras.models',
              'venv.lib.python3.6.site-packages.tensorflow.python.keras.backend',
              'venv.lib.python3.6.site-packages.tensorflow.python.keras.metrics',
              'venv.lib.python3.6.site-packages.tensorflow.python.keras.datasets',
              'venv.lib.python3.6.site-packages.tensorflow.python.keras.datasets.imdb',
              'venv.lib.python3.6.site-packages.tensorflow.python.keras.datasets.mnist',
              'venv.lib.python3.6.site-packages.tensorflow.python.keras.datasets.cifar10',
              'venv.lib.python3.6.site-packages.tensorflow.python.keras.datasets.reuters',
              'venv.lib.python3.6.site-packages.tensorflow.python.keras.datasets.cifar100',
              'venv.lib.python3.6.site-packages.tensorflow.python.keras.datasets.fashion_mnist',
              'venv.lib.python3.6.site-packages.tensorflow.python.keras.datasets.boston_housing',
              'venv.lib.python3.6.site-packages.tensorflow.python.keras.wrappers',
              'venv.lib.python3.6.site-packages.tensorflow.python.keras.wrappers.scikit_learn',
              'venv.lib.python3.6.site-packages.tensorflow.python.keras.callbacks',
              'venv.lib.python3.6.site-packages.tensorflow.python.keras.estimator',
              'venv.lib.python3.6.site-packages.tensorflow.python.keras.optimizers',
              'venv.lib.python3.6.site-packages.tensorflow.python.keras.activations',
              'venv.lib.python3.6.site-packages.tensorflow.python.keras.constraints',
              'venv.lib.python3.6.site-packages.tensorflow.python.keras.applications',
              'venv.lib.python3.6.site-packages.tensorflow.python.keras.applications.vgg16',
              'venv.lib.python3.6.site-packages.tensorflow.python.keras.applications.vgg19',
              'venv.lib.python3.6.site-packages.tensorflow.python.keras.applications.nasnet',
              'venv.lib.python3.6.site-packages.tensorflow.python.keras.applications.densenet',
              'venv.lib.python3.6.site-packages.tensorflow.python.keras.applications.resnet50',
              'venv.lib.python3.6.site-packages.tensorflow.python.keras.applications.xception',
              'venv.lib.python3.6.site-packages.tensorflow.python.keras.applications.mobilenet',
              'venv.lib.python3.6.site-packages.tensorflow.python.keras.applications.inception_v3',
              'venv.lib.python3.6.site-packages.tensorflow.python.keras.applications.inception_resnet_v2',
              'venv.lib.python3.6.site-packages.tensorflow.python.keras.initializers',
              'venv.lib.python3.6.site-packages.tensorflow.python.keras.regularizers',
              'venv.lib.python3.6.site-packages.tensorflow.python.keras.preprocessing',
              'venv.lib.python3.6.site-packages.tensorflow.python.keras.preprocessing.text',
              'venv.lib.python3.6.site-packages.tensorflow.python.keras.preprocessing.image',
              'venv.lib.python3.6.site-packages.tensorflow.python.keras.preprocessing.sequence',
              'venv.lib.python3.6.site-packages.tensorflow.python.tools',
              'venv.lib.python3.6.site-packages.tensorflow.python.client',
              'venv.lib.python3.6.site-packages.tensorflow.python.layers',
              'venv.lib.python3.6.site-packages.tensorflow.python.summary',
              'venv.lib.python3.6.site-packages.tensorflow.python.summary.writer',
              'venv.lib.python3.6.site-packages.tensorflow.python.grappler',
              'venv.lib.python3.6.site-packages.tensorflow.python.platform',
              'venv.lib.python3.6.site-packages.tensorflow.python.profiler',
              'venv.lib.python3.6.site-packages.tensorflow.python.profiler.internal',
              'venv.lib.python3.6.site-packages.tensorflow.python.training',
              'venv.lib.python3.6.site-packages.tensorflow.python.user_ops',
              'venv.lib.python3.6.site-packages.tensorflow.python.estimator',
              'venv.lib.python3.6.site-packages.tensorflow.python.estimator.canned',
              'venv.lib.python3.6.site-packages.tensorflow.python.estimator.export',
              'venv.lib.python3.6.site-packages.tensorflow.python.estimator.inputs',
              'venv.lib.python3.6.site-packages.tensorflow.python.estimator.inputs.queues',
              'venv.lib.python3.6.site-packages.tensorflow.python.framework',
              'venv.lib.python3.6.site-packages.tensorflow.python.saved_model',
              'venv.lib.python3.6.site-packages.tensorflow.python.feature_column',
              'venv.lib.python3.6.site-packages.tensorflow.contrib',
              'venv.lib.python3.6.site-packages.tensorflow.contrib.nn',
              'venv.lib.python3.6.site-packages.tensorflow.contrib.nn.python',
              'venv.lib.python3.6.site-packages.tensorflow.contrib.nn.python.ops',
              'venv.lib.python3.6.site-packages.tensorflow.contrib.crf',
              'venv.lib.python3.6.site-packages.tensorflow.contrib.crf.python',
              'venv.lib.python3.6.site-packages.tensorflow.contrib.crf.python.ops',
              'venv.lib.python3.6.site-packages.tensorflow.contrib.gan',
              'venv.lib.python3.6.site-packages.tensorflow.contrib.gan.python',
              'venv.lib.python3.6.site-packages.tensorflow.contrib.gan.python.eval',
              'venv.lib.python3.6.site-packages.tensorflow.contrib.gan.python.eval.python',
              'venv.lib.python3.6.site-packages.tensorflow.contrib.gan.python.losses',
              'venv.lib.python3.6.site-packages.tensorflow.contrib.gan.python.losses.python',
              'venv.lib.python3.6.site-packages.tensorflow.contrib.gan.python.features',
              'venv.lib.python3.6.site-packages.tensorflow.contrib.gan.python.features.python',
              'venv.lib.python3.6.site-packages.tensorflow.contrib.gan.python.estimator',
              'venv.lib.python3.6.site-packages.tensorflow.contrib.gan.python.estimator.python',
              'venv.lib.python3.6.site-packages.tensorflow.contrib.opt',
              'venv.lib.python3.6.site-packages.tensorflow.contrib.opt.python',
              'venv.lib.python3.6.site-packages.tensorflow.contrib.opt.python.training',
              'venv.lib.python3.6.site-packages.tensorflow.contrib.rnn',
              'venv.lib.python3.6.site-packages.tensorflow.contrib.rnn.ops',
              'venv.lib.python3.6.site-packages.tensorflow.contrib.rnn.python',
              'venv.lib.python3.6.site-packages.tensorflow.contrib.rnn.python.ops',
              'venv.lib.python3.6.site-packages.tensorflow.contrib.rnn.python.tools',
              'venv.lib.python3.6.site-packages.tensorflow.contrib.rnn.python.kernel_tests',
              'venv.lib.python3.6.site-packages.tensorflow.contrib.rpc',
              'venv.lib.python3.6.site-packages.tensorflow.contrib.rpc.python',
              'venv.lib.python3.6.site-packages.tensorflow.contrib.rpc.python.ops',
              'venv.lib.python3.6.site-packages.tensorflow.contrib.rpc.python.kernel_tests',
              'venv.lib.python3.6.site-packages.tensorflow.contrib.tpu',
              'venv.lib.python3.6.site-packages.tensorflow.contrib.tpu.ops',
              'venv.lib.python3.6.site-packages.tensorflow.contrib.tpu.proto',
              'venv.lib.python3.6.site-packages.tensorflow.contrib.tpu.python',
              'venv.lib.python3.6.site-packages.tensorflow.contrib.tpu.python.ops',
              'venv.lib.python3.6.site-packages.tensorflow.contrib.tpu.python.tpu',
              'venv.lib.python3.6.site-packages.tensorflow.contrib.tpu.python.profiler',
              'venv.lib.python3.6.site-packages.tensorflow.contrib.tpu.profiler',
              'venv.lib.python3.6.site-packages.tensorflow.contrib.data',
              'venv.lib.python3.6.site-packages.tensorflow.contrib.data.python',
              'venv.lib.python3.6.site-packages.tensorflow.contrib.data.python.ops',
              'venv.lib.python3.6.site-packages.tensorflow.contrib.data.python.kernel_tests',
              'venv.lib.python3.6.site-packages.tensorflow.contrib.kfac',
              'venv.lib.python3.6.site-packages.tensorflow.contrib.kfac.python',
              'venv.lib.python3.6.site-packages.tensorflow.contrib.kfac.python.ops',
              'venv.lib.python3.6.site-packages.tensorflow.contrib.lite',
              'venv.lib.python3.6.site-packages.tensorflow.contrib.lite.toco',
              'venv.lib.python3.6.site-packages.tensorflow.contrib.lite.toco.python',
              'venv.lib.python3.6.site-packages.tensorflow.contrib.lite.python',
              'venv.lib.python3.6.site-packages.tensorflow.contrib.nccl',
              'venv.lib.python3.6.site-packages.tensorflow.contrib.nccl.ops',
              'venv.lib.python3.6.site-packages.tensorflow.contrib.nccl.python',
              'venv.lib.python3.6.site-packages.tensorflow.contrib.nccl.python.ops',
              'venv.lib.python3.6.site-packages.tensorflow.contrib.slim',
              'venv.lib.python3.6.site-packages.tensorflow.contrib.slim.python',
              'venv.lib.python3.6.site-packages.tensorflow.contrib.slim.python.slim',
              'venv.lib.python3.6.site-packages.tensorflow.contrib.slim.python.slim.data',
              'venv.lib.python3.6.site-packages.tensorflow.contrib.slim.python.slim.nets',
              'venv.lib.python3.6.site-packages.tensorflow.contrib.text',
              'venv.lib.python3.6.site-packages.tensorflow.contrib.text.python',
              'venv.lib.python3.6.site-packages.tensorflow.contrib.text.python.ops',
              'venv.lib.python3.6.site-packages.tensorflow.contrib.util',
              'venv.lib.python3.6.site-packages.tensorflow.contrib.cloud',
              'venv.lib.python3.6.site-packages.tensorflow.contrib.cloud.python',
              'venv.lib.python3.6.site-packages.tensorflow.contrib.cloud.python.ops',
              'venv.lib.python3.6.site-packages.tensorflow.contrib.cmake',
              'venv.lib.python3.6.site-packages.tensorflow.contrib.cmake.tools',
              'venv.lib.python3.6.site-packages.tensorflow.contrib.coder',
              'venv.lib.python3.6.site-packages.tensorflow.contrib.coder.python',
              'venv.lib.python3.6.site-packages.tensorflow.contrib.coder.python.ops',
              'venv.lib.python3.6.site-packages.tensorflow.contrib.eager',
              'venv.lib.python3.6.site-packages.tensorflow.contrib.eager.proto',
              'venv.lib.python3.6.site-packages.tensorflow.contrib.eager.python',
              'venv.lib.python3.6.site-packages.tensorflow.contrib.eager.python.examples',
              'venv.lib.python3.6.site-packages.tensorflow.contrib.eager.python.examples.gan',
              'venv.lib.python3.6.site-packages.tensorflow.contrib.eager.python.examples.spinn',
              'venv.lib.python3.6.site-packages.tensorflow.contrib.eager.python.examples.rnn_ptb',
              'venv.lib.python3.6.site-packages.tensorflow.contrib.eager.python.examples.resnet50',
              'venv.lib.python3.6.site-packages.tensorflow.contrib.eager.python.examples.rnn_colorbot',
              'venv.lib.python3.6.site-packages.tensorflow.contrib.eager.python.examples.linear_regression',
              'venv.lib.python3.6.site-packages.tensorflow.contrib.hooks',
              'venv.lib.python3.6.site-packages.tensorflow.contrib.hooks.python',
              'venv.lib.python3.6.site-packages.tensorflow.contrib.hooks.python.training',
              'venv.lib.python3.6.site-packages.tensorflow.contrib.image',
              'venv.lib.python3.6.site-packages.tensorflow.contrib.image.ops',
              'venv.lib.python3.6.site-packages.tensorflow.contrib.image.python',
              'venv.lib.python3.6.site-packages.tensorflow.contrib.image.python.ops',
              'venv.lib.python3.6.site-packages.tensorflow.contrib.kafka',
              'venv.lib.python3.6.site-packages.tensorflow.contrib.kafka.python',
              'venv.lib.python3.6.site-packages.tensorflow.contrib.kafka.python.ops',
              'venv.lib.python3.6.site-packages.tensorflow.contrib.keras',
              'venv.lib.python3.6.site-packages.tensorflow.contrib.keras.api',
              'venv.lib.python3.6.site-packages.tensorflow.contrib.keras.api.keras',
              'venv.lib.python3.6.site-packages.tensorflow.contrib.keras.api.keras.utils',
              'venv.lib.python3.6.site-packages.tensorflow.contrib.keras.api.keras.layers',
              'venv.lib.python3.6.site-packages.tensorflow.contrib.keras.api.keras.losses',
              'venv.lib.python3.6.site-packages.tensorflow.contrib.keras.api.keras.models',
              'venv.lib.python3.6.site-packages.tensorflow.contrib.keras.api.keras.backend',
              'venv.lib.python3.6.site-packages.tensorflow.contrib.keras.api.keras.metrics',
              'venv.lib.python3.6.site-packages.tensorflow.contrib.keras.api.keras.datasets',
              'venv.lib.python3.6.site-packages.tensorflow.contrib.keras.api.keras.datasets.imdb',
              'venv.lib.python3.6.site-packages.tensorflow.contrib.keras.api.keras.datasets.mnist',
              'venv.lib.python3.6.site-packages.tensorflow.contrib.keras.api.keras.datasets.cifar10',
              'venv.lib.python3.6.site-packages.tensorflow.contrib.keras.api.keras.datasets.reuters',
              'venv.lib.python3.6.site-packages.tensorflow.contrib.keras.api.keras.datasets.cifar100',
              'venv.lib.python3.6.site-packages.tensorflow.contrib.keras.api.keras.datasets.boston_housing',
              'venv.lib.python3.6.site-packages.tensorflow.contrib.keras.api.keras.wrappers',
              'venv.lib.python3.6.site-packages.tensorflow.contrib.keras.api.keras.wrappers.scikit_learn',
              'venv.lib.python3.6.site-packages.tensorflow.contrib.keras.api.keras.callbacks',
              'venv.lib.python3.6.site-packages.tensorflow.contrib.keras.api.keras.optimizers',
              'venv.lib.python3.6.site-packages.tensorflow.contrib.keras.api.keras.activations',
              'venv.lib.python3.6.site-packages.tensorflow.contrib.keras.api.keras.constraints',
              'venv.lib.python3.6.site-packages.tensorflow.contrib.keras.api.keras.applications',
              'venv.lib.python3.6.site-packages.tensorflow.contrib.keras.api.keras.applications.vgg16',
              'venv.lib.python3.6.site-packages.tensorflow.contrib.keras.api.keras.applications.vgg19',
              'venv.lib.python3.6.site-packages.tensorflow.contrib.keras.api.keras.applications.resnet50',
              'venv.lib.python3.6.site-packages.tensorflow.contrib.keras.api.keras.applications.xception',
              'venv.lib.python3.6.site-packages.tensorflow.contrib.keras.api.keras.applications.mobilenet',
              'venv.lib.python3.6.site-packages.tensorflow.contrib.keras.api.keras.applications.inception_v3',
              'venv.lib.python3.6.site-packages.tensorflow.contrib.keras.api.keras.initializers',
              'venv.lib.python3.6.site-packages.tensorflow.contrib.keras.api.keras.regularizers',
              'venv.lib.python3.6.site-packages.tensorflow.contrib.keras.api.keras.preprocessing',
              'venv.lib.python3.6.site-packages.tensorflow.contrib.keras.api.keras.preprocessing.text',
              'venv.lib.python3.6.site-packages.tensorflow.contrib.keras.api.keras.preprocessing.image',
              'venv.lib.python3.6.site-packages.tensorflow.contrib.keras.api.keras.preprocessing.sequence',
              'venv.lib.python3.6.site-packages.tensorflow.contrib.learn',
              'venv.lib.python3.6.site-packages.tensorflow.contrib.learn.python',
              'venv.lib.python3.6.site-packages.tensorflow.contrib.learn.python.learn',
              'venv.lib.python3.6.site-packages.tensorflow.contrib.learn.python.learn.ops',
              'venv.lib.python3.6.site-packages.tensorflow.contrib.learn.python.learn.utils',
              'venv.lib.python3.6.site-packages.tensorflow.contrib.learn.python.learn.datasets',
              'venv.lib.python3.6.site-packages.tensorflow.contrib.learn.python.learn.learn_io',
              'venv.lib.python3.6.site-packages.tensorflow.contrib.learn.python.learn.estimators',
              'venv.lib.python3.6.site-packages.tensorflow.contrib.learn.python.learn.preprocessing',
              'venv.lib.python3.6.site-packages.tensorflow.contrib.learn.python.learn.preprocessing.tests',
              'venv.lib.python3.6.site-packages.tensorflow.contrib.proto',
              'venv.lib.python3.6.site-packages.tensorflow.contrib.proto.python',
              'venv.lib.python3.6.site-packages.tensorflow.contrib.proto.python.ops',
              'venv.lib.python3.6.site-packages.tensorflow.contrib.proto.python.kernel_tests',
              'venv.lib.python3.6.site-packages.tensorflow.contrib.specs',
              'venv.lib.python3.6.site-packages.tensorflow.contrib.specs.python',
              'venv.lib.python3.6.site-packages.tensorflow.contrib.ffmpeg',
              'venv.lib.python3.6.site-packages.tensorflow.contrib.ffmpeg.ops',
              'venv.lib.python3.6.site-packages.tensorflow.contrib.layers',
              'venv.lib.python3.6.site-packages.tensorflow.contrib.layers.ops',
              'venv.lib.python3.6.site-packages.tensorflow.contrib.layers.python',
              'venv.lib.python3.6.site-packages.tensorflow.contrib.layers.python.ops',
              'venv.lib.python3.6.site-packages.tensorflow.contrib.layers.python.layers',
              'venv.lib.python3.6.site-packages.tensorflow.contrib.libsvm',
              'venv.lib.python3.6.site-packages.tensorflow.contrib.libsvm.ops',
              'venv.lib.python3.6.site-packages.tensorflow.contrib.libsvm.python',
              'venv.lib.python3.6.site-packages.tensorflow.contrib.libsvm.python.ops',
              'venv.lib.python3.6.site-packages.tensorflow.contrib.linalg',
              'venv.lib.python3.6.site-packages.tensorflow.contrib.linalg.python',
              'venv.lib.python3.6.site-packages.tensorflow.contrib.linalg.python.ops',
              'venv.lib.python3.6.site-packages.tensorflow.contrib.lookup',
              'venv.lib.python3.6.site-packages.tensorflow.contrib.losses',
              'venv.lib.python3.6.site-packages.tensorflow.contrib.losses.python',
              'venv.lib.python3.6.site-packages.tensorflow.contrib.losses.python.losses',
              'venv.lib.python3.6.site-packages.tensorflow.contrib.losses.python.metric_learning',
              'venv.lib.python3.6.site-packages.tensorflow.contrib.signal',
              'venv.lib.python3.6.site-packages.tensorflow.contrib.signal.python',
              'venv.lib.python3.6.site-packages.tensorflow.contrib.signal.python.ops',
              'venv.lib.python3.6.site-packages.tensorflow.contrib.signal.python.kernel_tests',
              'venv.lib.python3.6.site-packages.tensorflow.contrib.tfprof',
              'venv.lib.python3.6.site-packages.tensorflow.contrib.metrics',
              'venv.lib.python3.6.site-packages.tensorflow.contrib.metrics.python',
              'venv.lib.python3.6.site-packages.tensorflow.contrib.metrics.python.ops',
              'venv.lib.python3.6.site-packages.tensorflow.contrib.metrics.python.metrics',
              'venv.lib.python3.6.site-packages.tensorflow.contrib.seq2seq',
              'venv.lib.python3.6.site-packages.tensorflow.contrib.seq2seq.ops',
              'venv.lib.python3.6.site-packages.tensorflow.contrib.seq2seq.python',
              'venv.lib.python3.6.site-packages.tensorflow.contrib.seq2seq.python.ops',
              'venv.lib.python3.6.site-packages.tensorflow.contrib.solvers',
              'venv.lib.python3.6.site-packages.tensorflow.contrib.solvers.python',
              'venv.lib.python3.6.site-packages.tensorflow.contrib.solvers.python.ops',
              'venv.lib.python3.6.site-packages.tensorflow.contrib.staging',
              'venv.lib.python3.6.site-packages.tensorflow.contrib.summary',
              'venv.lib.python3.6.site-packages.tensorflow.contrib.testing',
              'venv.lib.python3.6.site-packages.tensorflow.contrib.testing.python',
              'venv.lib.python3.6.site-packages.tensorflow.contrib.testing.python.framework',
              'venv.lib.python3.6.site-packages.tensorflow.contrib.batching',
              'venv.lib.python3.6.site-packages.tensorflow.contrib.batching.python',
              'venv.lib.python3.6.site-packages.tensorflow.contrib.batching.python.ops',
              'venv.lib.python3.6.site-packages.tensorflow.contrib.compiler',
              'venv.lib.python3.6.site-packages.tensorflow.contrib.grid_rnn',
              'venv.lib.python3.6.site-packages.tensorflow.contrib.grid_rnn.python',
              'venv.lib.python3.6.site-packages.tensorflow.contrib.grid_rnn.python.ops',
              'venv.lib.python3.6.site-packages.tensorflow.contrib.quantize',
              'venv.lib.python3.6.site-packages.tensorflow.contrib.quantize.python',
              'venv.lib.python3.6.site-packages.tensorflow.contrib.training',
              'venv.lib.python3.6.site-packages.tensorflow.contrib.training.python',
              'venv.lib.python3.6.site-packages.tensorflow.contrib.training.python.training',
              'venv.lib.python3.6.site-packages.tensorflow.contrib.autograph',
              'venv.lib.python3.6.site-packages.tensorflow.contrib.autograph.impl',
              'venv.lib.python3.6.site-packages.tensorflow.contrib.autograph.pyct',
              'venv.lib.python3.6.site-packages.tensorflow.contrib.autograph.pyct.static_analysis',
              'venv.lib.python3.6.site-packages.tensorflow.contrib.autograph.utils',
              'venv.lib.python3.6.site-packages.tensorflow.contrib.autograph.operators',
              'venv.lib.python3.6.site-packages.tensorflow.contrib.autograph.converters',
              'venv.lib.python3.6.site-packages.tensorflow.contrib.bayesflow',
              'venv.lib.python3.6.site-packages.tensorflow.contrib.bayesflow.python',
              'venv.lib.python3.6.site-packages.tensorflow.contrib.bayesflow.python.ops',
              'venv.lib.python3.6.site-packages.tensorflow.contrib.cudnn_rnn',
              'venv.lib.python3.6.site-packages.tensorflow.contrib.cudnn_rnn.python',
              'venv.lib.python3.6.site-packages.tensorflow.contrib.cudnn_rnn.python.ops',
              'venv.lib.python3.6.site-packages.tensorflow.contrib.cudnn_rnn.python.layers',
              'venv.lib.python3.6.site-packages.tensorflow.contrib.estimator',
              'venv.lib.python3.6.site-packages.tensorflow.contrib.estimator.python',
              'venv.lib.python3.6.site-packages.tensorflow.contrib.estimator.python.estimator',
              'venv.lib.python3.6.site-packages.tensorflow.contrib.framework',
              'venv.lib.python3.6.site-packages.tensorflow.contrib.framework.python',
              'venv.lib.python3.6.site-packages.tensorflow.contrib.framework.python.ops',
              'venv.lib.python3.6.site-packages.tensorflow.contrib.framework.python.framework',
              'venv.lib.python3.6.site-packages.tensorflow.contrib.integrate',
              'venv.lib.python3.6.site-packages.tensorflow.contrib.integrate.python',
              'venv.lib.python3.6.site-packages.tensorflow.contrib.integrate.python.ops',
              'venv.lib.python3.6.site-packages.tensorflow.contrib.predictor',
              'venv.lib.python3.6.site-packages.tensorflow.contrib.recurrent',
              'venv.lib.python3.6.site-packages.tensorflow.contrib.recurrent.python',
              'venv.lib.python3.6.site-packages.tensorflow.contrib.recurrent.python.ops',
              'venv.lib.python3.6.site-packages.tensorflow.contrib.resampler',
              'venv.lib.python3.6.site-packages.tensorflow.contrib.resampler.ops',
              'venv.lib.python3.6.site-packages.tensorflow.contrib.resampler.python',
              'venv.lib.python3.6.site-packages.tensorflow.contrib.resampler.python.ops',
              'venv.lib.python3.6.site-packages.tensorflow.contrib.sparsemax',
              'venv.lib.python3.6.site-packages.tensorflow.contrib.sparsemax.python',
              'venv.lib.python3.6.site-packages.tensorflow.contrib.sparsemax.python.ops',
              'venv.lib.python3.6.site-packages.tensorflow.contrib.stateless',
              'venv.lib.python3.6.site-packages.tensorflow.contrib.all_reduce',
              'venv.lib.python3.6.site-packages.tensorflow.contrib.all_reduce.python',
              'venv.lib.python3.6.site-packages.tensorflow.contrib.copy_graph',
              'venv.lib.python3.6.site-packages.tensorflow.contrib.copy_graph.python',
              'venv.lib.python3.6.site-packages.tensorflow.contrib.copy_graph.python.util',
              'venv.lib.python3.6.site-packages.tensorflow.contrib.deprecated',
              'venv.lib.python3.6.site-packages.tensorflow.contrib.distribute',
              'venv.lib.python3.6.site-packages.tensorflow.contrib.distribute.python',
              'venv.lib.python3.6.site-packages.tensorflow.contrib.fused_conv',
              'venv.lib.python3.6.site-packages.tensorflow.contrib.fused_conv.ops',
              'venv.lib.python3.6.site-packages.tensorflow.contrib.fused_conv.python',
              'venv.lib.python3.6.site-packages.tensorflow.contrib.fused_conv.python.ops',
              'venv.lib.python3.6.site-packages.tensorflow.contrib.timeseries',
              'venv.lib.python3.6.site-packages.tensorflow.contrib.timeseries.python',
              'venv.lib.python3.6.site-packages.tensorflow.contrib.timeseries.python.timeseries',
              'venv.lib.python3.6.site-packages.tensorflow.contrib.timeseries.python.timeseries.state_space_models',
              'venv.lib.python3.6.site-packages.tensorflow.contrib.timeseries.examples',
              'venv.lib.python3.6.site-packages.tensorflow.contrib.saved_model',
              'venv.lib.python3.6.site-packages.tensorflow.contrib.saved_model.python',
              'venv.lib.python3.6.site-packages.tensorflow.contrib.saved_model.python.saved_model',
              'venv.lib.python3.6.site-packages.tensorflow.contrib.tensorboard',
              'venv.lib.python3.6.site-packages.tensorflow.contrib.tensorboard.plugins',
              'venv.lib.python3.6.site-packages.tensorflow.contrib.tensorboard.plugins.trace',
              'venv.lib.python3.6.site-packages.tensorflow.contrib.tensorboard.plugins.projector',
              'venv.lib.python3.6.site-packages.tensorflow.contrib.tensorboard.graph_explorer',
              'venv.lib.python3.6.site-packages.tensorflow.contrib.tensorboard.graph_explorer.proto',
              'venv.lib.python3.6.site-packages.tensorflow.contrib.graph_editor',
              'venv.lib.python3.6.site-packages.tensorflow.contrib.graph_editor.tests',
              'venv.lib.python3.6.site-packages.tensorflow.contrib.memory_stats',
              'venv.lib.python3.6.site-packages.tensorflow.contrib.memory_stats.ops',
              'venv.lib.python3.6.site-packages.tensorflow.contrib.memory_stats.python',
              'venv.lib.python3.6.site-packages.tensorflow.contrib.memory_stats.python.ops',
              'venv.lib.python3.6.site-packages.tensorflow.contrib.optimizer_v2',
              'venv.lib.python3.6.site-packages.tensorflow.contrib.quantization',
              'venv.lib.python3.6.site-packages.tensorflow.contrib.quantization.python',
              'venv.lib.python3.6.site-packages.tensorflow.contrib.boosted_trees',
              'venv.lib.python3.6.site-packages.tensorflow.contrib.boosted_trees.lib',
              'venv.lib.python3.6.site-packages.tensorflow.contrib.boosted_trees.lib.learner',
              'venv.lib.python3.6.site-packages.tensorflow.contrib.boosted_trees.lib.learner.batch',
              'venv.lib.python3.6.site-packages.tensorflow.contrib.boosted_trees.proto',
              'venv.lib.python3.6.site-packages.tensorflow.contrib.boosted_trees.python',
              'venv.lib.python3.6.site-packages.tensorflow.contrib.boosted_trees.python.ops',
              'venv.lib.python3.6.site-packages.tensorflow.contrib.boosted_trees.python.utils',
              'venv.lib.python3.6.site-packages.tensorflow.contrib.boosted_trees.python.training',
              'venv.lib.python3.6.site-packages.tensorflow.contrib.boosted_trees.python.training.functions',
              'venv.lib.python3.6.site-packages.tensorflow.contrib.boosted_trees.estimator_batch',
              'venv.lib.python3.6.site-packages.tensorflow.contrib.distributions',
              'venv.lib.python3.6.site-packages.tensorflow.contrib.distributions.python',
              'venv.lib.python3.6.site-packages.tensorflow.contrib.distributions.python.ops',
              'venv.lib.python3.6.site-packages.tensorflow.contrib.distributions.python.ops.bijectors',
              'venv.lib.python3.6.site-packages.tensorflow.contrib.factorization',
              'venv.lib.python3.6.site-packages.tensorflow.contrib.factorization.python',
              'venv.lib.python3.6.site-packages.tensorflow.contrib.factorization.python.ops',
              'venv.lib.python3.6.site-packages.tensorflow.contrib.model_pruning',
              'venv.lib.python3.6.site-packages.tensorflow.contrib.model_pruning.python',
              'venv.lib.python3.6.site-packages.tensorflow.contrib.model_pruning.python.layers',
              'venv.lib.python3.6.site-packages.tensorflow.contrib.tensor_forest',
              'venv.lib.python3.6.site-packages.tensorflow.contrib.tensor_forest.proto',
              'venv.lib.python3.6.site-packages.tensorflow.contrib.tensor_forest.client',
              'venv.lib.python3.6.site-packages.tensorflow.contrib.tensor_forest.hybrid',
              'venv.lib.python3.6.site-packages.tensorflow.contrib.tensor_forest.hybrid.ops',
              'venv.lib.python3.6.site-packages.tensorflow.contrib.tensor_forest.hybrid.python',
              'venv.lib.python3.6.site-packages.tensorflow.contrib.tensor_forest.hybrid.python.ops',
              'venv.lib.python3.6.site-packages.tensorflow.contrib.tensor_forest.hybrid.python.layers',
              'venv.lib.python3.6.site-packages.tensorflow.contrib.tensor_forest.hybrid.python.models',
              'venv.lib.python3.6.site-packages.tensorflow.contrib.tensor_forest.python',
              'venv.lib.python3.6.site-packages.tensorflow.contrib.tensor_forest.python.ops',
              'venv.lib.python3.6.site-packages.tensorflow.contrib.decision_trees',
              'venv.lib.python3.6.site-packages.tensorflow.contrib.decision_trees.proto',
              'venv.lib.python3.6.site-packages.tensorflow.contrib.feature_column',
              'venv.lib.python3.6.site-packages.tensorflow.contrib.feature_column.python',
              'venv.lib.python3.6.site-packages.tensorflow.contrib.feature_column.python.feature_column',
              'venv.lib.python3.6.site-packages.tensorflow.contrib.input_pipeline',
              'venv.lib.python3.6.site-packages.tensorflow.contrib.input_pipeline.ops',
              'venv.lib.python3.6.site-packages.tensorflow.contrib.input_pipeline.python',
              'venv.lib.python3.6.site-packages.tensorflow.contrib.input_pipeline.python.ops',
              'venv.lib.python3.6.site-packages.tensorflow.contrib.kernel_methods',
              'venv.lib.python3.6.site-packages.tensorflow.contrib.kernel_methods.python',
              'venv.lib.python3.6.site-packages.tensorflow.contrib.kernel_methods.python.mappers',
              'venv.lib.python3.6.site-packages.tensorflow.contrib.labeled_tensor',
              'venv.lib.python3.6.site-packages.tensorflow.contrib.labeled_tensor.python',
              'venv.lib.python3.6.site-packages.tensorflow.contrib.labeled_tensor.python.ops',
              'venv.lib.python3.6.site-packages.tensorflow.contrib.legacy_seq2seq',
              'venv.lib.python3.6.site-packages.tensorflow.contrib.legacy_seq2seq.python',
              'venv.lib.python3.6.site-packages.tensorflow.contrib.legacy_seq2seq.python.ops',
              'venv.lib.python3.6.site-packages.tensorflow.contrib.session_bundle',
              'venv.lib.python3.6.site-packages.tensorflow.contrib.receptive_field',
              'venv.lib.python3.6.site-packages.tensorflow.contrib.receptive_field.python',
              'venv.lib.python3.6.site-packages.tensorflow.contrib.receptive_field.python.util',
              'venv.lib.python3.6.site-packages.tensorflow.contrib.stat_summarizer',
              'venv.lib.python3.6.site-packages.tensorflow.contrib.cluster_resolver',
              'venv.lib.python3.6.site-packages.tensorflow.contrib.cluster_resolver.python',
              'venv.lib.python3.6.site-packages.tensorflow.contrib.cluster_resolver.python.training',
              'venv.lib.python3.6.site-packages.tensorflow.contrib.linear_optimizer',
              'venv.lib.python3.6.site-packages.tensorflow.contrib.linear_optimizer.python',
              'venv.lib.python3.6.site-packages.tensorflow.contrib.linear_optimizer.python.ops',
              'venv.lib.python3.6.site-packages.tensorflow.contrib.nearest_neighbor',
              'venv.lib.python3.6.site-packages.tensorflow.contrib.nearest_neighbor.python',
              'venv.lib.python3.6.site-packages.tensorflow.contrib.nearest_neighbor.python.ops',
              'venv.lib.python3.6.site-packages.tensorflow.contrib.reduce_slice_ops',
              'venv.lib.python3.6.site-packages.tensorflow.contrib.reduce_slice_ops.ops',
              'venv.lib.python3.6.site-packages.tensorflow.contrib.reduce_slice_ops.python',
              'venv.lib.python3.6.site-packages.tensorflow.contrib.reduce_slice_ops.python.ops',
              'venv.lib.python3.6.site-packages.tensorflow.contrib.periodic_resample',
              'venv.lib.python3.6.site-packages.tensorflow.contrib.periodic_resample.python',
              'venv.lib.python3.6.site-packages.tensorflow.contrib.periodic_resample.python.ops',
              'venv.lib.python3.6.site-packages.tensorflow.contrib.remote_fused_graph',
              'venv.lib.python3.6.site-packages.tensorflow.contrib.remote_fused_graph.pylib',
              'venv.lib.python3.6.site-packages.tensorflow.contrib.remote_fused_graph.pylib.python',
              'venv.lib.python3.6.site-packages.tensorflow.contrib.remote_fused_graph.pylib.python.ops',
              'venv.lib.python3.6.site-packages.tensorflow.contrib.meta_graph_transform',
              'venv.lib.python3.6.site-packages.tensorflow.examples',
              'venv.lib.python3.6.site-packages.tensorflow.examples.tutorials',
              'venv.lib.python3.6.site-packages.tensorflow.examples.tutorials.mnist',
              'venv.lib.python3.6.site-packages.tensorboard', 'venv.lib.python3.6.site-packages.tensorboard.backend',
              'venv.lib.python3.6.site-packages.tensorboard.backend.event_processing',
              'venv.lib.python3.6.site-packages.tensorboard.plugins',
              'venv.lib.python3.6.site-packages.tensorboard.plugins.core',
              'venv.lib.python3.6.site-packages.tensorboard.plugins.text',
              'venv.lib.python3.6.site-packages.tensorboard.plugins.audio',
              'venv.lib.python3.6.site-packages.tensorboard.plugins.graph',
              'venv.lib.python3.6.site-packages.tensorboard.plugins.image',
              'venv.lib.python3.6.site-packages.tensorboard.plugins.scalar',
              'venv.lib.python3.6.site-packages.tensorboard.plugins.profile',
              'venv.lib.python3.6.site-packages.tensorboard.plugins.beholder',
              'venv.lib.python3.6.site-packages.tensorboard.plugins.debugger',
              'venv.lib.python3.6.site-packages.tensorboard.plugins.pr_curve',
              'venv.lib.python3.6.site-packages.tensorboard.plugins.histogram',
              'venv.lib.python3.6.site-packages.tensorboard.plugins.projector',
              'venv.lib.python3.6.site-packages.tensorboard.plugins.distribution',
              'venv.lib.python3.6.site-packages.tensorboard.plugins.custom_scalar',
              'venv.lib.python3.6.site-packages.tensorboard.pip_package',
              'venv.lib.python3.6.site-packages.mpl_toolkits.tests',
              'venv.lib.python3.6.site-packages.mpl_toolkits.mplot3d',
              'venv.lib.python3.6.site-packages.mpl_toolkits.axes_grid',
              'venv.lib.python3.6.site-packages.mpl_toolkits.axes_grid1',
              'venv.lib.python3.6.site-packages.mpl_toolkits.axisartist'],
    url='',
    license='',
    author='Ana Esmeralda, Rui Miranda, Thanira Rates',
    author_email='',
    description=''
)
